ATLAS-5002: Bundle commons-text in hbase-hook
1) commons-configuration2 in coprocessor without commons-text.jar on plugin CP
java.lang.NoClassDefFoundError: org/apache/commons/text/lookup/StringLookupFactory
	at org.apache.commons.configuration2.interpol.DefaultLookups.<clinit>(...)

Caused by: java.lang.ClassNotFoundException: org.apache.commons.text.lookup.StringLookupFactory
	at org.apache.atlas.plugin.classloader.AtlasPluginClassLoader$MyClassLoader.findClass(...)

Also surfaced as:
The coprocessor org.apache.atlas.hbase.hook.HBaseAtlasCoprocessor threw
java.lang.InstantiationException: org.apache.atlas.hbase.hook.HBaseAtlasCoprocessor